### ISSUE TITLE
Some channels don't Stream...

### ISSUE THREAD

**Issue by ThanosPrimo** [tninis/stremio-greek-tv#1]
Hi! There is some time now that some of the channels of the addon do not stream... (OPEN, ERT1, ERT2, ERT3, ANT1, MAKEDONIA TV, OPEN) Do you have any suggestions for what it may be the problem?

**Comment by tninis** [comment]
OPEN, ERT1, ERT2, ERT3 were fixed, new links have been uploaded .
Unfortunately for ANT1 and MAKEDONIA in order to watch live TV you need to be logged in to their sites (https://vod.antenna.gr/), there were links that was working for some time without any authentication but now do no work. Maybe in future these link will open again.
Please note that any link provided by the add-on is not maintained by me .
Thanks .

**Comment by ThanosPrimo** [comment]
Hi Theodor!
have you noticed problems in streaming of the ERT1-2-3-World ? They stream video from days that have passed...

**Comment by tninis** [comment]
Hi Thanos, 
Thanks for inform me , i updated the links and now should be working again.

**Comment by ThanosPrimo** [comment]
> Hi Thanos, Thanks for inform me , i updated the links and now should be working again.

Hi Theodor!
There's again the same problem with ERT... 😕

**Comment by tninis** [comment]
Hi Thanos, 
I have updated the links. Should be available in a few minutes. 
Unfortunately the link are keep changing . thanks for letting me know.

**Comment by ThanosPrimo** [comment]
Hey! Hi Theodor! :-)
What happened to the addon? :(
![image](https://user-images.githubusercontent.com/102465280/204790844-b3cf4f88-ff79-40f5-b8e5-3fdd2292d338.png)

**Comment by tninis** [comment]
Hello Thanos,
The addon was hosted on Heroku .
Unfortunately Heroku decided to change the free plans and i had to pay for the hosting.
I did some search for a free provider and found one . I am in process of hosting in there. I hope till end of the week the addon to be live again. thanks

**Comment by ThanosPrimo** [comment]
Excellent my friend!
Thank you once again! 😊


------ Original Message ------
From "Theodor Ninis" ***@***.***>
To "tninis/stremio-greek-tv" ***@***.***>
Cc "ThanosPrimo" ***@***.***>; "Author" 
***@***.***>
Date 30/11/2022 5:11:51 μμ
Subject Re: [tninis/stremio-greek-tv] Some channels don't Stream... 
(Issue #1)

**Comment by tninis** [comment]
Hello Thano, the addon is up and running , please remove the previous one , and install the new .  New link is https://grtv-prod-stremio-inzgmy.mo6.mogenius.io/manifest.json

**Comment by ThanosPrimo** [comment]
Hi Theodor!
Excellent! Thank u once again for your marvellous work! 😊
(btw, take a look at the OPEN channel, the link probably changed...)


------ Original Message ------
From "Theodor Ninis" ***@***.***>
To "tninis/stremio-greek-tv" ***@***.***>
Cc "ThanosPrimo" ***@***.***>; "Author" 
***@***.***>
Date 1/12/2022 8:35:17 μμ
Subject Re: [tninis/stremio-greek-tv] Some channels don't Stream... 
(Issue #1)

**Comment by tninis** [comment]
Link update . thanks thano

**Comment by ThanosPrimo** [comment]
Hey! Hi Theo! 
something's wrong with the plugin... 😏
![image](https://user-images.githubusercontent.com/102465280/208240937-7b25e89d-6697-469c-b76a-07a9c75e0ddf.png)

**Comment by tninis** [comment]
Hi Thano, there is an issue with the hosting provider, and currently is down. I will contact them to see what is happening.
