### ISSUE TITLE
The add-on doesn't seem to work anymore

### ISSUE THREAD

**Issue by MariaKou17** [tninis/stremio-greek-tv#4]
Hello, 

I can't get this add-on to work. I tried uninstalling and installing it again, I tried installing it from the Stremio Add-ons site. I copied both the available links for it, but still nothing. Is anyone else facing the same problem? Is there a fix or is the add-on down?

Thank you

**Comment by tninis** [comment]
now its working again.  the correct URL is : https://stremiogreektv.bsite.net/manifest.json
