### ISSUE TITLE
Greek Tv stremio does not work 

### ISSUE THREAD

**Issue by Amaliageor** [tninis/stremio-greek-tv#5]
Hello, does anyone know why Greek Tv add on in stremio does not work? It was the most useful add on for us outside Greece. 😭

**Comment by tninis** [comment]
Hello, yes there is an issue with the site certificate as it has been expired. I am working it with the host provider, but i cant do much as this is a free host provider and the configuration is limited.  If this is not resloved in next days i will try to find a new host provider

**Comment by tninis** [comment]
@Amaliageor  you can use the following link to use the addon : https://stremiogreektv.fly.dev/manifest.json
In next days will be added also to stremio addon list
